project:
  title: "dsip-quarto"

book:
  title: "Data Science and Machine Learning in Practice"
  output-file: dsip
  author: ["Peter Rush"
    "Matthew Brett"]
  chapters:
    - part: coding_background.md
      chapters:
      - assert.Rmd
      - arrays_and_images.Rmd
      - where_and_argmin.Rmd
      - where_2d.Rmd
      - image_for_optimize.Rmd
      - pathlib.Rmd
      - dictionaries.Rmd
      - pandas_and_dicts.Rmd
      - lambda_functions.Rmd
    - part: reading_formulae.md
      chapters:
      - numpy_and_vectors.Rmd
      - algebra_of_sums.Rmd
      - lin_regression_notation.Rmd
      - lin_regression_multiple_predictors.Rmd
    - part: data_work
    - part: tools
      chapters:
      - installation.md
      - the-problem-with-notebooks.Rmd
    - chapters:
    - index.Rmd
    - preface_third.Rmd
    - preface_second.Rmd
    - intro.Rmd
    - resampling_method.Rmd
    - what_is_probability.Rmd
    - about_technology.Rmd
    - resampling_with_code.Rmd
    - sampling_tools.Rmd
    - resampling_with_code2.Rmd
    - probability_theory_1a.Rmd
    - probability_theory_1b.Rmd
    - more_sampling_tools.Rmd
    - probability_theory_2_compound.Rmd
    - probability_theory_3.Rmd
    - probability_theory_4_finite.Rmd
    - sampling_variability.Rmd
    - monte_carlo.Rmd
    - standard_scores.Rmd
    - inference_ideas.Rmd
    - inference_intro.Rmd
    - point_estimation.Rmd
    - framing_questions.Rmd
    - testing_counts_1.Rmd
    - significance.Rmd
    - testing_counts_2.Rmd
    - testing_measured.Rmd
    - testing_procedures.Rmd
    - confidence_1.Rmd
    - confidence_2.Rmd
    - reliability_average.Rmd
    - correlation_causation.Rmd
    - how_big_sample.Rmd
    - bayes_simulation.Rmd
    - exercise_solutions.Rmd
    - acknowlegements.Rmd
    - technical_note.Rmd
    - references.Rmd

crossref:
  sec-prefix: Section     # (default is "sec.")
  fig-prefix: Figure      # (default is "fig.")
  tbl-prefix: Table       # (default is "tbl.")

bibliography: bib/course_refs.bib

format:
  html:
    theme: cosmo
    css: [style.css, font-awesome.min.css]
  pdf:
    documentclass: scrreport

filters:
  - quarto

knitr_settings:
  # Comment preceding code output.
  out_comment: ""

noteout:
  # Divs, spans to filter before further processing.
  pre-filter: ['todo', 'comment']
  filter-divspans: {filter_divspans}
  nb-flatten-divspans: {nb_flatten_divspans}
  nb-format: {nb_format}
  strip-header-nos: false
  binder-url: https://mybinder.org/v2/gh/resampling-stats/resampling-with/gh-pages?filepath={version}-book/
  nb-dir: notebooks
